### PR TITLE
translate jsx-loader.zh-CN.md，took 3hours10minutes

### PR DESCRIPTION
**Pull request by lijunhuippl**
There are some unnecessary files together. Only one file is useful--jsx-loader.zh-CN.md

### CODE REVIEW

**Comment by lijunhuippl** [comment]
I'll translate the playground's files tomorrow.

**Comment by ConradSollitt** [comment]
Thanks looks great!

For the playground basically the [en] template is copied and then code comments are updated.

A good example is if you compare the Spanish [es] version to English [en]:

https://www.dataformsjs.com/es/playground

**Comment by ConradSollitt** [comment]
For the hello world demos/text should `你好，世界！` be used instead of the English "Hello World!"?

If it's common to use in Chinese programming guides then it should be changed but I don't know if it's more common for Chinese programming guides to use the English version.

Example page:
https://www.dataformsjs.com/examples/hello-world/zh-CN/react.htm

`你好，世界！` is a verified translation on Google Translate

On the GoLang main page (at least when viewed in the US) they mix English and Chinese `fmt.Println("Hello, 世界")`:
https://golang.org/

**Comment by lijunhuippl** [comment]
No,all of the chinese programmer learn "hello,world " not "你好，世界".&nbsp;Because the first program we learned is "Hello, world". We are more accustomed to using "Hello world", not "你好,世界". I think "Hello, world" is universal in the world.It's the same when I was studying the program in Korea.After all, the program is all written in English~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conrad Sollitt"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 凌晨3:43
收件人: "dataformsjs/dataformsjs"<dataformsjs@noreply.github.com&gt;; 
抄送: "Wdihui"<951708552@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dataformsjs/dataformsjs] translate jsx-loader.zh-CN.md，took 3hours10minutes (#13)





 
For the hello world demos/text should 你好，世界！ be used instead of the English "Hello World!"?
 
If it's common to use in Chinese programming guides then it should be changed but I don't know if it's more common for Chinese programming guides to use the English version.
 
Example page:
 https://www.dataformsjs.com/examples/hello-world/zh-CN/react.htm
 
你好，世界！ is a verified translation on Google Translate
 
On the GoLang main page (at least when viewed in the US) they mix English and Chinese fmt.Println("Hello, 世界"):
 https://golang.org/

**Comment by ConradSollitt** [comment]
Great, Thanks for the insight!

**Comment by ConradSollitt** [comment]
@lijunhuippl @eGirlAsm 
FYI, I added your names with links back to your profile to give in the changelog to give you more credit for helping with translations
https://github.com/dataformsjs/dataformsjs/blob/master/CHANGELOG.md

Hope things are well and that you are staying safe!

**Comment by lijunhuippl** [comment]
Thanks!!!!!!!!!!!!!!!!!!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Conrad Sollitt"<notifications@github.com&gt;; 
发送时间: 2020年5月22日(星期五) 上午6:45
收件人: "dataformsjs/dataformsjs"<dataformsjs@noreply.github.com&gt;; 
抄送: "Wdihui"<951708552@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [dataformsjs/dataformsjs] translate jsx-loader.zh-CN.md，took 3hours10minutes (#13)





 
@lijunhuippl @eGirlAsm
 FYI, I added your names with links back to your profile to give in the changelog to give you more credit for helping with translations
 https://github.com/dataformsjs/dataformsjs/blob/master/CHANGELOG.md
 
Hope things are well and that you are staying safe!

**Pull request merged**
